import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import jwt from 'jsonwebtoken';
const app=express(); const PORT=Number(process.env.PORT||4000); const SECRET=process.env.JWT_SECRET||'dev-only-change-me';
app.use(helmet()); app.use(cors({origin:process.env.CORS_ORIGIN?.split(',')||['http://localhost:5173'],credentials:true})); app.use(express.json({limit:'1mb'})); app.use(rateLimit({windowMs:15*60*1000,max:120,standardHeaders:true,legacyHeaders:false}));
const users=[{id:'s1',name:'Sundram Student',username:'student',password:'sundram123',role:'student',batch:'Aarambh'},{id:'s2',name:'Abhay Student',username:'abhay',password:'sundram123',role:'student',batch:'Abhay'},{id:'a1',name:'Administrator',username:'admin',password:'sundram123',role:'admin',batch:'Aarambh'}];
const content=[{id:'n1',title:'Chemical Reactions & Equations',subject:'Science',chapter:'Chemical Reactions and Equations',type:'note',year:2026,batches:['Aarambh','Abhay'],published:true},{id:'n2',title:'Resources and Development',subject:'Social Science',chapter:'Resources and Development',type:'note',year:2026,batches:['Aarambh'],published:true},{id:'l1',title:'The Rise of Nationalism in Europe',subject:'History',chapter:'The Rise of Nationalism in Europe',type:'lecture',year:2026,batches:['Aarambh','Abhay'],published:true,url:'https://www.youtube.com/'},{id:'d1',title:'Electricity — DPP 01',subject:'Science',chapter:'Electricity',type:'dpp',year:2026,batches:['Aarambh'],published:true,difficulty:'Moderate'}];
function auth(req:any,res:any,next:any){const h=req.headers.authorization; if(!h?.startsWith('Bearer ')) return res.status(401).json({message:'Authentication required.'}); try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({message:'Authentication required.'})}}
function admin(req:any,res:any,next:any){if(req.user?.role!=='admin')return res.status(403).json({message:'You do not have permission to access this resource.'});next()}
app.post('/api/auth/login',(req,res)=>{const u=users.find(x=>x.username===req.body.username); if(!u||u.password!==req.body.password)return res.status(401).json({message:'Incorrect username or password.'}); const token=jwt.sign({id:u.id,username:u.username,role:u.role,batch:u.batch,name:u.name},SECRET,{expiresIn:'8h'});res.json({user:{id:u.id,name:u.name,username:u.username,role:u.role,batch:u.batch},token})});
app.post('/api/auth/logout',auth,(_,res)=>res.json({ok:true})); app.get('/api/auth/me',auth,(req:any,res)=>res.json({user:req.user}));
app.get('/api/content',auth,(req:any,res)=>{const q=String(req.query.q||'').toLowerCase(); const type=req.query.type?String(req.query.type):undefined; const out=content.filter(c=>c.published&&c.batches.includes(req.user.batch)&&(!type||c.type===type)&&(!q||JSON.stringify(c).toLowerCase().includes(q)));res.json({items:out,page:1,limit:20,total:out.length})});
app.get('/api/content/:id',auth,(req:any,res)=>{const c=content.find(x=>x.id===req.params.id);if(!c||!c.published||!c.batches.includes(req.user.batch))return res.status(403).json({message:'You do not have permission to access this content.'});res.json({content:c})});
app.get('/api/admin/students',auth,admin,(_,res)=>res.json({items:users.map(({password,...u})=>u)}));
app.get('/api/admin/stats',auth,admin,(_,res)=>res.json({students:users.filter(u=>u.role==='student').length,aarambh:users.filter(u=>u.batch==='Aarambh').length,abhay:users.filter(u=>u.batch==='Abhay').length,notes:content.filter(c=>c.type==='note').length,lectures:content.filter(c=>c.type==='lecture').length,dpp:content.filter(c=>c.type==='dpp').length}));
app.post('/api/practice/:id/start',auth,(req,res)=>res.json({attemptId:`attempt-${Date.now()}`,startedAt:new Date().toISOString()}));
app.post('/api/practice/:id/submit',auth,(req,res)=>res.json({score:1,total:1,percentage:100,correctAnswers:1,incorrectAnswers:0}));
app.post('/api/ai/chat',auth,(req,res)=>{if(!process.env.LLM_API_KEY)return res.status(503).json({message:'Sundram AI is currently unavailable. Your other study resources are still available.'});res.status(501).json({message:'Configure your LLM provider to enable AI.'})});
app.use((_,res)=>res.status(404).json({message:'The requested resource was not found.'})); app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({message:'Something went wrong on our side. Please try again later.'})}); app.listen(PORT,()=>console.log(`Sundram API running on http://localhost:${PORT}`));
